import cv2 
image=cv2.imread("d:\\cv\\pro.jpg")
print(image.shape)
print("Do U wat to draw the shapes??")
ger=input("Yes / NO")
if(ger=='y'):
    print("Which shape do U want to draw")
    op=int(input("1) Line        2) Rectange      3) Circle     4) Text   "))
    match op:
        case 1:
            color=(0,0,255)
            x1=int(input(" Enter the values of X1 "))
            y1=int(input("Enter the value of y1"))
            p1=(x1,y1)
            x2=int(input("Enter the value of X2"))
            y2=int(input("Enter the value of Y2"))
            p2=(x2,y2)
            thickness=int(input("Enter the thickness"))
            temp=cv2.line(image,p1,p2, color, thickness)
            cv2.imshow("Image showing with line", temp)
            cv2.waitKey(0)
            cv2.destroyAllWindows()
        case 2:
            color=(0,0,255)
            x1=int(input(" Enter the values of X1 "))
            y1=int(input("Enter the value of y1"))
            p1=(x1,y1)
            x2=int(input("Enter the value of X2"))
            y2=int(input("Enter the value of Y2"))
            p2=(x2,y2)
            thickness=int(input("Enter the thickness"))
            temp1=cv2.rectangle(image,p1,p2, color, thickness)
            cv2.imshow("Image showing with line", temp1)
            cv2.waitKey(0)
            cv2.destroyAllWindows()
        case 3:
            color=(0,0,255)
            x1=int(input(" Enter the values of X1 "))
            y1=int(input("Enter the value of y1"))
            center=(x1,y1)
            thickness=int(input("Enter the thickness"))
            radius=int(input("Enter the radius "))
            temp2=cv2.circle(image,center, radius,color, thickness)
            cv2.imshow("Image showing with line", temp2)
            cv2.waitKey(0)
            cv2.destroyAllWindows()
        case 4:
             color=(0,0,255)
             x1=int(input(" Enter the values of X1 "))
             y1=int(input("Enter the value of y1"))
             center=(x1,y1)
             thickness=int(input("Enter the thickness"))
             temp3=cv2.putText(image, "Oh !! it is a tree ", center , cv2.FONT_HERSHEY_SIMPLEX, 2, color , 5)
             cv2.imshow("Image showing with line", temp3)
             cv2.waitKey(0)
             cv2.destroyAllWindows()
            
            
else:
    print("Picture without any shape ")
    cv2.imshow("showing the image", image)
    cv2.waitKey(0)
    cv2.destroyAllWindows() 